const themes=[
  {id:'nocturne',name:'夜航玻璃',note:'深夜蓝 · 香槟金',bg:'#0b1322',panel:'#132139',accent:'#e4b863',text:'#edf3fb',muted:'#92a2b8',swatches:['#0b1322','#7c9cc4','#e4b863']},
  {id:'ocean',name:'月光海湾',note:'海军蓝 · 冰川蓝',bg:'#091724',panel:'#102b3c',accent:'#72c6dc',text:'#edf8fb',muted:'#9bb9c3',swatches:['#091724','#368aa7','#72c6dc']},
  {id:'forest',name:'苔原森林',note:'松针绿 · 柔和鼠尾草',bg:'#101b1b',panel:'#1b302d',accent:'#91c3a2',text:'#eef7f0',muted:'#a2b7aa',swatches:['#101b1b','#477a64','#91c3a2']},
  {id:'violet',name:'暮色鸢尾',note:'石板紫 · 淡紫罗兰',bg:'#171522',panel:'#27243a',accent:'#b7a5e8',text:'#f2eff9',muted:'#b1abc3',swatches:['#171522','#7261a3','#b7a5e8']},
  {id:'amber',name:'琥珀实验室',note:'石墨黑 · 蜂蜜琥珀',bg:'#1b1711',panel:'#30261a',accent:'#e9b45f',text:'#fbf4e8',muted:'#c2b39b',swatches:['#1b1711','#986b32','#e9b45f']},
  {id:'paper',name:'实验记录纸',note:'暖白 · 实验室蓝',bg:'#eef2f5',panel:'#ffffff',accent:'#347aa5',text:'#172430',muted:'#5e6c76',swatches:['#eef2f5','#347aa5','#77a78e']}
];
const state={plasmids:[],groups:[],synonymClusters:[],previews:{},noteDrafts:{},selected:null,view:'library',groupFilter:null,featureQuery:'',activeFeature:null,search:'',searchDetails:true,sortOrder:'name_asc',toastTimer:null,storage:null,theme:'nocturne',closeBehavior:'ask'};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLocaleLowerCase().replace(/[\s_-]+/g,'');
const fileNameCollator=new Intl.Collator('zh-CN',{numeric:true,sensitivity:'base'});
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`请求失败 (${r.status})`);return data}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function groupName(){if(state.view==='favorites')return '我的收藏';if(state.view==='recent')return '最近查看';return state.groupFilter===null?'全部质粒':state.groups.find(g=>g.id===state.groupFilter)?.name||'全部质粒'}
function synonymTerms(q){const n=norm(q),cluster=state.synonymClusters.find(c=>c.terms.some(term=>norm(term)===n));return cluster?cluster.terms.map(norm):[n]}
function matches(p,q){if(!q)return true;const terms=synonymTerms(q),hay=[p.name,...(state.searchDetails?p.tags:[]),...(state.searchDetails?[p.note]:[])].map(norm);return terms.some(term=>term&&hay.some(t=>t.includes(term)))}
function pickerMatches(p,q,includeDetails){if(!q)return true;const terms=synonymTerms(q),hay=[p.name,...(includeDetails?p.tags:[]),...(includeDetails?[p.note]:[])].map(norm);return terms.some(term=>term&&hay.some(value=>value.includes(term)))}
function dragExportDescriptor(p,origin){return `application/octet-stream:${p.name.replace(/[\r\n:]/g,'_')}:${origin}/api/file/${p.id}`}
function hitBadge(p,q){if(!q||!state.searchDetails)return '';const terms=synonymTerms(q),tag=p.tags.find(tag=>terms.some(t=>norm(tag).includes(t)));if(tag)return `<span class="tag-chip primary">标签 · ${esc(tag)}</span>`;return terms.some(t=>t&&norm(p.note).includes(t))?'<span class="tag-chip primary">备注匹配</span>':''}
function filtered(){return state.plasmids.filter(p=>(state.view==='favorites'?p.favorite:state.view==='recent'?!!p.lastViewedAt:state.groupFilter===null||p.groupIds.includes(state.groupFilter))&&matches(p,state.search))}
function sortedPlasmids(items){const byName=(a,b)=>fileNameCollator.compare(a.name,b.name)||a.id-b.id;if(state.view==='recent')return [...items].sort((a,b)=>b.lastViewedAt.localeCompare(a.lastViewedAt)||byName(a,b));const order=state.sortOrder;return [...items].sort((a,b)=>{if(order==='name_desc')return -byName(a,b);if(order==='import_new')return b.importedAt.localeCompare(a.importedAt)||byName(a,b);if(order==='import_old')return a.importedAt.localeCompare(b.importedAt)||byName(a,b);if(order==='size_large')return b.size-a.size||byName(a,b);if(order==='size_small')return a.size-b.size||byName(a,b);return byName(a,b)})}
function renderGroups(){const box=$('#group-list');box.innerHTML=state.groups.map(g=>`<button class="group-row ${state.view==='library'&&state.groupFilter===g.id?'active':''}" data-group="${g.id}" title="可拖入 .dna 文件；右键管理分组"><i class="group-dot"></i><span>${esc(g.name)}</span><span class="group-num">${g.count}</span></button>`).join('');box.querySelectorAll('[data-group]').forEach(b=>{b.onclick=()=>{closeContextMenu();state.groupFilter=Number(b.dataset.group);state.view='library';state.selected=null;render()};b.oncontextmenu=e=>{e.preventDefault();openGroupActions(Number(b.dataset.group),e)}})}
function renderList(){const list=$('#plasmid-list'),items=sortedPlasmids(filtered());$('#all-count').textContent=state.plasmids.length;$('#favorite-count').textContent=state.plasmids.filter(p=>p.favorite).length;$('#recent-count').textContent=state.plasmids.filter(p=>p.lastViewedAt).length;$('#stat-count').textContent=items.length;$('#result-count').textContent=`${items.length} 个结果`;
 if(!items.length){const empty=state.view==='favorites'&&!state.search?'尚无收藏的质粒':state.view==='recent'&&!state.search?'尚无最近查看的质粒':state.plasmids.length?'没有匹配的质粒':'尚未导入质粒。点击右上角“导入质粒”添加 .dna 文件。';list.innerHTML=`<div class="no-results">${empty}</div>`;return}
 list.innerHTML=items.map(p=>{const accession=(p.name.match(/\bJH\d+\b/i)||[])[0]||'DNA';const tags=p.tags.slice(0,3);return `<article class="plasmid-card ${state.selected===p.id?'selected':''}" data-id="${p.id}" draggable="false" title="拖出卡片可复制 .dna 文件；按住 Shift 拖到分组可加入分组；右键管理质粒"><div class="plasmid-title-row"><span class="plasmid-id">${esc(accession)}</span><span class="plasmid-name" title="拖到资源管理器可复制 ${esc(p.name)}">${esc(p.name)}</span><button class="favorite-toggle ${p.favorite?'is-favorite':''}" type="button" data-favorite="${p.id}" aria-label="${p.favorite?'取消收藏':'收藏质粒'}" title="${p.favorite?'取消收藏':'收藏质粒'}">${p.favorite?'★':'☆'}</button></div><div class="plasmid-meta"><span>${(p.size/1024/1024).toFixed(2)} MB</span><span>导入于 ${esc(p.importedAt.slice(0,10))}</span></div><div class="mini-tags">${hitBadge(p,state.search)}${tags.map(t=>`<span class="tag-chip">${esc(t)}</span>`).join('')}</div></article>`}).join('');list.querySelectorAll('[data-id]').forEach(el=>{el.onclick=()=>{closeContextMenu();selectPlasmid(Number(el.dataset.id))};el.oncontextmenu=e=>{e.preventDefault();openPlasmidActions(Number(el.dataset.id),e)};el.onmousedown=e=>{if(e.button!==0||e.target.closest('.favorite-toggle'))return;el.draggable=!!e.shiftKey;el._dragStart=e.shiftKey?null:{x:e.clientX,y:e.clientY,id:Number(el.dataset.id)}};el.onmousemove=e=>{const start=el._dragStart;if(!start||!(e.buttons&1))return;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)<8)return;el._dragStart=null;if(!window.pywebview?.api?.start_file_drag){toast('请在桌面程序中拖出质粒');return}window.pywebview.api.start_file_drag(start.id).then(result=>{if(result.error)toast(result.error)}).catch(error=>toast(error.message))};el.onmouseup=()=>{el._dragStart=null;el.draggable=false};el.ondragstart=e=>{const p=state.plasmids.find(x=>x.id===Number(el.dataset.id));if(!p)return;e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('application/x-plasmora-id',String(p.id))};el.ondragend=()=>{el._dragStart=null;el.draggable=false;clearDropVisual()}});list.querySelectorAll('[data-favorite]').forEach(button=>button.onclick=e=>{e.stopPropagation();toggleFavorite(Number(button.dataset.favorite))})}
const typeColors={CDS:'#e4b863',promoter:'#80a9d2',rep_origin:'#7cb79f',enhancer:'#c899ba',terminator:'#91a9c4',polyA_signal:'#c8a477',regulatory:'#be9564',intron:'#8c99aa',primer_bind:'#83bab7',protein_bind:'#c18b77'};
function color(f){return typeColors[f.type]||'var(--accent)'}
function polar(r,pos,len){const a=-Math.PI/2+(pos-1)/len*Math.PI*2;return [170+r*Math.cos(a),170+r*Math.sin(a)]}
function arcPath(start,end,r,len){if(start===end)return '';let s=start,e=end;if(e<s)e+=len;const [x1,y1]=polar(r,s,len),[x2,y2]=polar(r,e,len),large=e-s>len/2?1:0;return `M ${x1.toFixed(2)} ${y1.toFixed(2)} A ${r} ${r} 0 ${large} 1 ${x2.toFixed(2)} ${y2.toFixed(2)}`}
function renderMap(p){const drawn=p.features.flatMap((f,i)=>f.segments.map(seg=>({f,i,seg}))).filter(x=>x.seg[0]>=1&&x.seg[1]<=p.length).slice(0,100);const paths=drawn.map(x=>{const r=112+(x.i%4)*10;return `<path class="feature-arc" data-feature="${x.i}" data-feature-name="${esc(x.f.name)}" d="${arcPath(x.seg[0],x.seg[1],r,p.length)}" stroke="${color(x.f)}"/>`}).join('');return `<div class="map-wrap"><svg class="map-svg" viewBox="0 0 340 340" role="img" aria-label="质粒 feature 环状图谱"><circle class="map-ring" cx="170" cy="170" r="127"/><circle class="map-inner" cx="170" cy="170" r="48"/>${paths}<text class="map-center-title" x="170" y="165">${p.length.toLocaleString()} bp</text><text class="map-center-sub" x="170" y="184">${p.circular?'CIRCULAR':'LINEAR'}</text></svg><div class="map-tooltip" id="map-tooltip" role="tooltip"></div><div class="map-caption">${drawn.length} 个注释区段 · 悬停查看名称，点击查看注释</div></div>`}
function renderFeatures(p){const q=norm(state.featureQuery),features=p.features.filter(f=>!q||norm(`${f.name} ${f.type} ${f.searchText}`).includes(q));const rows=features.map(f=>{const original=p.features.indexOf(f),range=f.segments.map(s=>`${s[0].toLocaleString()}–${s[1].toLocaleString()}`).join(', ');const detail=state.activeFeature===original?`<div class="feature-detail">${Object.entries(f.qualifiers||{}).map(([k,v])=>`<div><strong>${esc(k)}:</strong> ${esc(v.join('; '))}</div>`).join('')||'此 feature 没有额外注释。'}<div>方向：${f.direction===1?'正向':f.direction===2?'反向':'未标注'}</div></div>`:'';return `<div class="feature-row" data-feature-row="${original}"><i class="feature-swatch" style="background:${color(f)}"></i><div><div class="feature-label">${esc(f.name)}</div><div class="feature-kind">${esc(f.type)}</div>${detail}</div><span class="feature-range">${range||'—'}</span></div>`}).join('');return `<div class="detail-section"><div class="section-title"><span>Feature 注释</span><small>${features.length} / ${p.features.length}</small></div><input class="feature-search" id="feature-search" placeholder="在这个质粒内筛选 feature…" value="${esc(state.featureQuery)}"/><div>${rows||'<div class="no-results">没有匹配的 feature</div>'}</div></div>`}
function renderAssignments(p){const groups=state.groups.filter(g=>p.groupIds.includes(g.id));return `<div class="detail-section"><div class="section-title"><span>所属分组</span><small>仅显示 · 右键质粒可修改</small></div><div class="group-chips">${groups.length?groups.map(g=>`<span class="group-label">${esc(g.name)}</span>`).join(''):'<span class="subtitle">尚未加入分组</span>'}</div></div>`}
function renderNote(p){const value=state.noteDrafts[p.id]??p.note??'';return `<div class="detail-section plasmid-note-section"><div class="section-title"><span>备注</span><small>仅保存在本机仓库</small></div><textarea class="plasmid-note" id="plasmid-note" maxlength="10000" placeholder="记录来源、构建信息或实验提示…">${esc(value)}</textarea><div class="note-footer"><span id="note-length">${value.length} / 10000</span><button class="button button-gold" id="save-note" type="button">保存备注</button></div></div>`}
function renderDetail(){const meta=state.plasmids.find(x=>x.id===state.selected),panel=$('#detail-panel');if(!meta){panel.innerHTML=`<div class="empty-detail"><div class="empty-orbit">⌁</div><h2>选择一个质粒</h2><p>打开时才读取原件并解析 feature</p></div>`;return}const preview=state.previews[meta.id];if(!preview||preview.loading){panel.innerHTML=`<div class="detail-head"><div><h2>${esc(meta.name)}</h2><div class="detail-sub">${(meta.size/1024/1024).toFixed(2)} MB · 本机原件</div></div></div><div class="loading">正在读取原件并生成预览…</div>`;if(!preview){state.previews[meta.id]={loading:true};loadPreview(meta.id)}return}if(preview.error){panel.innerHTML=`<div class="detail-head"><div><h2>${esc(meta.name)}</h2></div><a class="small-icon" href="/api/file/${meta.id}" download title="下载原始文件">⇩</a></div><div class="no-results">${esc(preview.error)}</div>`;return}const p=preview;panel.innerHTML=`<div class="detail-head"><div><h2>${esc(meta.name)}</h2><div class="detail-sub">${p.length.toLocaleString()} bp&nbsp;&nbsp;·&nbsp;&nbsp;${p.circular?'环状序列':'线性序列'}&nbsp;&nbsp;·&nbsp;&nbsp;${p.features.length} 个 feature</div></div><div class="detail-actions"><a class="small-icon" href="/api/file/${meta.id}" download title="下载原始文件" style="display:grid;place-items:center;text-decoration:none">⇩</a><button class="small-icon" id="copy-name" title="复制文件名">⧉</button></div></div>${renderMap(p)}<div class="map-legend">${[['CDS','#e4b863'],['Promoter','#80a9d2'],['Origin','#7cb79f'],['Other','#7d91ad']].map(([n,c])=>`<span><i class="legend-dot" style="background:${c}"></i>${n}</span>`).join('')}</div>${renderAssignments(meta)}${renderFeatures(p)}<div class="detail-section"><div class="section-title"><span>仓库信息</span><small>SHA-256</small></div><div class="feature-detail">${esc(state.storage?.path||'')}<br/><span style="font-family:'DM Mono',monospace;font-size:9px;word-break:break-all">${esc(meta.sha256)}</span></div></div>`;
 panel.querySelector('.detail-actions').insertAdjacentHTML('afterbegin',`<button class="small-icon detail-favorite ${meta.favorite?'is-favorite':''}" id="detail-favorite" title="${meta.favorite?'取消收藏':'收藏质粒'}" aria-label="${meta.favorite?'取消收藏':'收藏质粒'}">${meta.favorite?'★':'☆'}</button>`);$('#detail-favorite').onclick=()=>toggleFavorite(meta.id);panel.querySelector('.detail-section').insertAdjacentHTML('beforebegin',renderNote(meta));const noteInput=$('#plasmid-note');noteInput.oninput=()=>{state.noteDrafts[meta.id]=noteInput.value;$('#note-length').textContent=`${noteInput.value.length} / 10000`};$('#save-note').onclick=async()=>{const button=$('#save-note');button.disabled=true;try{const result=await api(`/api/plasmids/${meta.id}/note`,{method:'PATCH',body:JSON.stringify({note:noteInput.value})});meta.note=result.note;delete state.noteDrafts[meta.id];renderList();toast('备注已保存')}catch(err){toast(err.message)}finally{button.disabled=false}};
 const tooltip=$('#map-tooltip'),map=$('.map-wrap');panel.querySelectorAll('.feature-arc').forEach(el=>{el.addEventListener('click',()=>{state.activeFeature=Number(el.dataset.feature);renderDetail()});el.addEventListener('pointerenter',e=>{tooltip.textContent=el.dataset.featureName;tooltip.classList.add('visible');placeMapTooltip(e,map,tooltip)});el.addEventListener('pointermove',e=>placeMapTooltip(e,map,tooltip));el.addEventListener('pointerleave',()=>tooltip.classList.remove('visible'))});panel.querySelectorAll('[data-feature-row]').forEach(el=>el.addEventListener('click',()=>{state.activeFeature=Number(el.dataset.featureRow);renderDetail()}));$('#feature-search').addEventListener('input',e=>{state.featureQuery=e.target.value;const pos=e.target.selectionStart;renderDetail();const input=$('#feature-search');input.focus();input.setSelectionRange(pos,pos)});$('#copy-name').onclick=async()=>{await navigator.clipboard.writeText(meta.name);toast('文件名已复制')}}
function placeMapTooltip(e,map,tooltip){const rect=map.getBoundingClientRect();tooltip.style.left=`${Math.max(8,Math.min(e.clientX-rect.left+12,rect.width-tooltip.offsetWidth-8))}px`;tooltip.style.top=`${Math.max(8,e.clientY-rect.top-36)}px`}
async function loadPreview(id){try{const d=await api(`/api/plasmids/${id}/preview`);state.previews[id]=d;if(d.metadataChanged){await loadPlasmids();renderList();toast('检测到原件修改，Feature 标签和校验值已同步')}}catch(e){state.previews[id]={error:e.message}}if(state.selected===id)renderDetail()}
function selectPlasmid(id){state.selected=id;state.activeFeature=null;state.featureQuery='';const item=state.plasmids.find(p=>p.id===id);if(item)item.lastViewedAt=new Date().toISOString();renderList();renderDetail();api(`/api/plasmids/${id}/view`,{method:'POST',body:'{}'}).then(result=>{if(item)item.lastViewedAt=result.lastViewedAt;renderList()}).catch(err=>toast(err.message))}
async function toggleFavorite(id){const item=state.plasmids.find(p=>p.id===id);if(!item)return;try{const result=await api(`/api/plasmids/${id}/favorite`,{method:'PATCH',body:JSON.stringify({favorite:!item.favorite})});item.favorite=result.favorite;if(state.view==='favorites'&&!item.favorite&&state.selected===id)state.selected=null;render();toast(item.favorite?'已收藏质粒':'已取消收藏')}catch(err){toast(err.message)}}
function closeContextMenu(){const menu=$('#context-menu');menu.classList.add('hidden');menu.replaceChildren()}
function openContextMenu(event,items,onSelect){const menu=$('#context-menu');menu.innerHTML=items.map(([key,label,kind=''])=>`<button type="button" class="context-item ${kind}" role="menuitem" data-action="${key}">${esc(label)}</button>`).join('');menu.style.left='0px';menu.style.top='0px';menu.classList.remove('hidden');const rect=menu.getBoundingClientRect(),gap=8;menu.style.left=`${Math.max(gap,Math.min(event.clientX,window.innerWidth-rect.width-gap))}px`;menu.style.top=`${Math.max(gap,Math.min(event.clientY,window.innerHeight-rect.height-gap))}px`;menu.onclick=e=>{const button=e.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;closeContextMenu();onSelect(action)};menu.querySelector('button')?.focus({preventScroll:true})}
function closeActionDialog(){$('#action-modal').classList.add('hidden');$('#action-content').innerHTML=''}
function openActionDialog(title,subtitle,content,eyebrow='LIBRARY ACTION'){closeContextMenu();$('#action-title').textContent=title;$('#action-subtitle').textContent=subtitle;$('#action-eyebrow').textContent=eyebrow;$('#action-content').innerHTML=content;$('#action-modal').classList.remove('hidden');$('#action-content button, #action-content input')?.focus()}
function openPlasmidActions(id,event){const p=state.plasmids.find(x=>x.id===id);if(!p)return;openContextMenu(event,[['snapgene','在 SnapGene 中打开'],['export','导出 .dna 文件'],['rename','重命名质粒'],['groups','修改质粒分组'],['delete','删除质粒','danger']],async action=>{if(action==='export')exportSinglePlasmid(id);if(action==='rename')openRenamePlasmid(id);if(action==='groups')openPlasmidGroups(id);if(action==='delete')openDeletePlasmid(id);if(action==='snapgene'){if(!window.pywebview?.api?.open_in_snapgene){toast('请在桌面程序中打开 SnapGene');return}try{const result=await window.pywebview.api.open_in_snapgene(id);if(result.error)throw new Error(result.error);toast(result.method==='association'?'已用 .dna 关联程序打开':'已在 SnapGene 中打开')}catch(err){toast(err.message)}}})}
async function exportSinglePlasmid(id){if(!window.pywebview?.api?.export_plasmid){toast('请在 Plasmora 桌面程序中导出');return}try{const result=await window.pywebview.api.export_plasmid(id);if(result.cancelled)return;if(result.error)throw new Error(result.error);toast(`已导出 ${result.name}`)}catch(err){toast(err.message)}}
function openGroupActions(id,event){const g=state.groups.find(x=>x.id===id);if(!g)return;openContextMenu(event,[['rename','重命名分组'],['delete','删除分组','danger']],action=>{if(action==='rename')openRenameGroup(id);if(action==='delete')openDeleteGroup(id)})}
function openRenamePlasmid(id){const p=state.plasmids.find(x=>x.id===id);if(!p)return;openActionDialog('重命名质粒','只更改仓库中的显示文件名，DNA 原件内容保持不变。',`<form class="action-form" id="rename-plasmid-form"><input name="name" value="${esc(p.name)}" maxlength="200" required/><div class="dialog-buttons"><button type="button" class="button" id="cancel-action">取消</button><button class="button button-gold" type="submit">保存名称</button></div></form>`);$('#cancel-action').onclick=closeActionDialog;$('#rename-plasmid-form').onsubmit=async e=>{e.preventDefault();try{await api(`/api/plasmids/${id}`,{method:'PATCH',body:JSON.stringify({name:new FormData(e.target).get('name')})});await loadPlasmids();render();closeActionDialog();toast('质粒名称已更新')}catch(err){toast(err.message)}}}
function openRenameGroup(id){const g=state.groups.find(x=>x.id===id);if(!g)return;openActionDialog('重命名分组','分组内的质粒不会改变。',`<form class="action-form" id="rename-group-form"><input name="name" value="${esc(g.name)}" maxlength="40" required/><div class="dialog-buttons"><button type="button" class="button" id="cancel-action">取消</button><button class="button button-gold" type="submit">保存名称</button></div></form>`);$('#cancel-action').onclick=closeActionDialog;$('#rename-group-form').onsubmit=async e=>{e.preventDefault();try{await api(`/api/groups/${id}`,{method:'PATCH',body:JSON.stringify({name:new FormData(e.target).get('name')})});await loadGroups();await loadPlasmids();render();closeActionDialog();toast('分组名称已更新')}catch(err){toast(err.message)}}}
function openDeletePlasmid(id){const p=state.plasmids.find(x=>x.id===id);if(!p)return;openActionDialog('确认删除质粒',`“${p.name}”将移入回收站，保留原件、备注和分组，之后可以恢复。`,`<div class="dialog-buttons"><button class="button" id="cancel-action">取消</button><button class="button danger-button" id="confirm-delete">移入回收站</button></div>`,'SECOND CONFIRMATION');$('#cancel-action').onclick=closeActionDialog;$('#confirm-delete').onclick=async()=>{try{await api(`/api/plasmids/${id}`,{method:'DELETE'});delete state.previews[id];if(state.selected===id)state.selected=null;await Promise.all([loadPlasmids(),loadGroups()]);render();closeActionDialog();toast('质粒已移入回收站')}catch(err){toast(err.message)}}}
function openDeleteGroup(id){const g=state.groups.find(x=>x.id===id);if(!g)return;openActionDialog('确认删除分组',`将删除“${g.name}”分组；其中的质粒仍保留在总仓库。`,`<div class="dialog-buttons"><button class="button" id="cancel-action">取消</button><button class="button danger-button" id="confirm-delete">确认删除分组</button></div>`,'SECOND CONFIRMATION');$('#cancel-action').onclick=closeActionDialog;$('#confirm-delete').onclick=async()=>{try{await api(`/api/groups/${id}`,{method:'DELETE'});if(state.groupFilter===id)state.groupFilter=null;await Promise.all([loadGroups(),loadPlasmids()]);render();closeActionDialog();toast('分组已删除')}catch(err){toast(err.message)}}}
function syncSelectAll(master,ids,selected){const count=ids.filter(id=>selected.has(id)).length;master.disabled=!ids.length;master.checked=ids.length>0&&count===ids.length;master.indeterminate=count>0&&count<ids.length}
function openPlasmidGroups(id){const p=state.plasmids.find(x=>x.id===id);if(!p)return;const selected=new Set(p.groupIds);openActionDialog('修改质粒分组',p.name,`${state.groups.length?'<label class="select-all-row"><input type="checkbox" id="groups-select-all"/><span>全选分组</span></label>':''}<div class="choice-list" id="membership-list">${state.groups.map(g=>`<label class="choice-row"><input type="checkbox" value="${g.id}" ${selected.has(g.id)?'checked':''}/><span>${esc(g.name)}</span></label>`).join('')||'<p class="subtitle">尚未创建分组。请先从侧栏新建分组。</p>'}</div><div class="dialog-buttons"><button class="button" id="cancel-action">取消</button><button class="button button-gold" id="save-memberships">保存分组</button></div>`);const master=$('#groups-select-all'),list=$('#membership-list');if(master){const sync=()=>syncSelectAll(master,state.groups.map(g=>g.id),new Set([...list.querySelectorAll('input:checked')].map(el=>Number(el.value))));master.onchange=()=>{list.querySelectorAll('input[type=checkbox]').forEach(el=>el.checked=master.checked);sync()};list.onchange=sync;sync()}$('#cancel-action').onclick=closeActionDialog;$('#save-memberships').onclick=async()=>{const desired=new Set([...list.querySelectorAll('input:checked')].map(el=>Number(el.value)));try{for(const gid of desired)if(!selected.has(gid))await api(`/api/groups/${gid}/plasmids`,{method:'POST',body:JSON.stringify({plasmid_id:id})});for(const gid of selected)if(!desired.has(gid))await api(`/api/groups/${gid}/plasmids/${id}`,{method:'DELETE'});await Promise.all([loadGroups(),loadPlasmids()]);render();closeActionDialog();toast('质粒分组已更新')}catch(err){toast(err.message)}}}
function openGroupPicker(id){const g=state.groups.find(x=>x.id===id);if(!g)return;const selected=new Set(state.plasmids.filter(p=>p.groupIds.includes(id)).map(p=>p.id));openActionDialog(`添加到“${g.name}”`,'从全部质粒中勾选，保存后更新这个分组。',`<input class="picker-search" id="picker-search" placeholder="搜索全部质粒…" autocomplete="off"/><label class="picker-scope"><input type="checkbox" id="picker-search-details" ${state.searchDetails?'checked':''}/><span>包含 Feature 与备注</span></label><label class="select-all-row"><input type="checkbox" id="picker-select-all"/><span id="picker-select-all-label">全选全部质粒</span></label><div class="picker-count" id="picker-count"></div><div class="choice-list plasmid-picker" id="picker-list"></div><div class="dialog-buttons"><button class="button" id="cancel-action">取消</button><button class="button button-gold" id="save-group-picker">保存分组</button></div>`,'SELECT PLASMIDS');const list=$('#picker-list'),master=$('#picker-select-all');let visible=[];function update(){syncSelectAll(master,visible.map(p=>p.id),selected);$('#picker-count').textContent=`已选 ${selected.size} / 全部 ${state.plasmids.length}`};function draw(){const q=$('#picker-search').value.trim(),includeDetails=$('#picker-search-details').checked;visible=state.plasmids.filter(p=>pickerMatches(p,q,includeDetails));$('#picker-select-all-label').textContent=q?'全选当前搜索结果':'全选全部质粒';list.innerHTML=visible.map(p=>`<label class="choice-row"><input type="checkbox" value="${p.id}" ${selected.has(p.id)?'checked':''}/><span>${esc(p.name)}</span></label>`).join('')||'<div class="no-results">没有匹配的质粒</div>';update()};draw();$('#picker-search').oninput=draw;$('#picker-search-details').onchange=draw;master.onchange=()=>{for(const p of visible){if(master.checked)selected.add(p.id);else selected.delete(p.id)}draw()};list.onchange=e=>{if(!e.target.matches('input[type=checkbox]'))return;const id=Number(e.target.value);if(e.target.checked)selected.add(id);else selected.delete(id);update()};$('#cancel-action').onclick=closeActionDialog;$('#save-group-picker').onclick=async()=>{try{await api(`/api/groups/${id}/members`,{method:'POST',body:JSON.stringify({plasmid_ids:[...selected]})});await Promise.all([loadGroups(),loadPlasmids()]);render();closeActionDialog();toast('分组质粒已更新')}catch(err){toast(err.message)}}}
function openBulkExport(){const eligible=sortedPlasmids(filtered());if(!eligible.length){toast('当前列表没有可导出的质粒');return}const selected=new Set(eligible.map(p=>p.id));openActionDialog('批量导出质粒',`从当前列表的 ${eligible.length} 个质粒中选择，导出为 ZIP 文件并附带清单。`,`<input class="picker-search" id="export-search" placeholder="在当前列表中搜索…" autocomplete="off"/><label class="select-all-row"><input type="checkbox" id="export-select-all"/><span id="export-select-label">全选当前列表</span></label><div class="picker-count" id="export-count"></div><div class="choice-list plasmid-picker" id="export-list"></div><div class="dialog-buttons"><button class="button" id="cancel-action">取消</button><button class="button button-gold" id="save-export">选择保存位置</button></div>`,'BULK EXPORT');const list=$('#export-list'),master=$('#export-select-all');let visible=[];function update(){syncSelectAll(master,visible.map(p=>p.id),selected);$('#export-count').textContent=`已选 ${selected.size} / 当前列表 ${eligible.length}`};function draw(){const q=norm($('#export-search').value);visible=eligible.filter(p=>!q||norm(p.name).includes(q)||p.tags.some(t=>norm(t).includes(q))||norm(p.note).includes(q));$('#export-select-label').textContent=q?'全选当前搜索结果':'全选当前列表';list.innerHTML=visible.map(p=>`<label class="choice-row"><input type="checkbox" value="${p.id}" ${selected.has(p.id)?'checked':''}/><span>${esc(p.name)}</span></label>`).join('')||'<div class="no-results">没有匹配的质粒</div>';update()};draw();$('#export-search').oninput=draw;master.onchange=()=>{for(const p of visible){if(master.checked)selected.add(p.id);else selected.delete(p.id)}draw()};list.onchange=e=>{if(!e.target.matches('input[type=checkbox]'))return;const id=Number(e.target.value);if(e.target.checked)selected.add(id);else selected.delete(id);update()};$('#cancel-action').onclick=closeActionDialog;$('#save-export').onclick=async()=>{if(!selected.size){toast('请至少选择一个质粒');return}if(!window.pywebview?.api?.export_plasmids){toast('请在桌面程序中导出');return}const button=$('#save-export');button.disabled=true;try{const result=await window.pywebview.api.export_plasmids([...selected]);if(result.cancelled)return;if(result.error)throw new Error(result.error);closeActionDialog();toast(`已导出 ${result.count} 个质粒`)}catch(err){toast(err.message)}finally{button.disabled=false}}}
function openDataTools(){openActionDialog('备份与恢复','备份包含数据库、分组、同义词、备注及所有托管的 .dna 文件。',`<div class="data-tools"><button class="button button-gold" id="create-backup">创建完整备份</button><button class="button" id="choose-restore">从备份恢复</button></div>`,'LOCAL DATA');$('#create-backup').onclick=async()=>{if(!window.pywebview?.api?.backup_library){toast('请在桌面程序中备份');return}const button=$('#create-backup');button.disabled=true;try{const result=await window.pywebview.api.backup_library();if(result.cancelled)return;if(result.error)throw new Error(result.error);closeActionDialog();toast(`已备份 ${result.count} 个质粒`)}catch(err){toast(err.message)}finally{button.disabled=false}};$('#choose-restore').onclick=async()=>{if(!window.pywebview?.api?.choose_backup_for_restore){toast('请在桌面程序中恢复');return}const button=$('#choose-restore');button.disabled=true;try{const info=await window.pywebview.api.choose_backup_for_restore();if(info.cancelled)return;if(info.error)throw new Error(info.error);openActionDialog('确认恢复备份',`备份创建于 ${info.createdAt||'未知时间'}，包含 ${info.count} 个质粒。恢复会替换当前仓库的记录和托管文件。`,`<div class="dialog-buttons"><button class="button" id="cancel-action">取消</button><button class="button danger-button" id="confirm-restore">确认恢复</button></div>`,'CONFIRM RESTORE');$('#cancel-action').onclick=closeActionDialog;$('#confirm-restore').onclick=async()=>{const confirm=$('#confirm-restore');confirm.disabled=true;try{const result=await window.pywebview.api.restore_backup();if(result.error)throw new Error(result.error);state.previews={};state.noteDrafts={};state.selected=null;state.view='library';state.groupFilter=null;state.search='';$('#search').value='';await Promise.all([loadSettings(),loadPlasmids(),loadGroups(),loadSynonymClusters()]);render();renderSynonymClusters();renderThemes();closeActionDialog();toast(`已恢复 ${result.count} 个质粒`)}catch(err){toast(err.message)}finally{confirm.disabled=false}}}catch(err){toast(err.message)}finally{button.disabled=false}}}
function parseClusterTerms(value){return value.split(/[,，;；\n]+/).map(term=>term.trim()).filter(Boolean)}
function renderSynonymClusters(){const box=$('#cluster-list');box.innerHTML=state.synonymClusters.map(c=>`<div class="cluster-row"><div class="cluster-terms">${c.terms.map(term=>`<span class="cluster-term">${esc(term)}</span>`).join('')}</div><div class="cluster-actions"><button class="button" data-edit-cluster="${c.id}">编辑</button><button class="delete-link" data-delete-cluster="${c.id}">删除</button></div></div>`).join('')||'<div class="no-results">尚无同义词集群</div>';box.querySelectorAll('[data-edit-cluster]').forEach(b=>b.onclick=()=>openEditSynonymCluster(Number(b.dataset.editCluster)));box.querySelectorAll('[data-delete-cluster]').forEach(b=>b.onclick=()=>openDeleteSynonymCluster(Number(b.dataset.deleteCluster)))}
function openEditSynonymCluster(id){const cluster=state.synonymClusters.find(c=>c.id===id);if(!cluster)return;openActionDialog('编辑同义词集群','同一集群中的任意词都可以搜到其他词。加入另一集群的词会合并两个集群。',`<form class="action-form" id="edit-cluster-form"><textarea name="terms" class="cluster-editor" rows="5" required>${esc(cluster.terms.join('，'))}</textarea><div class="dialog-buttons"><button type="button" class="button" id="cancel-action">取消</button><button class="button button-gold" type="submit">保存集群</button></div></form>`);$('#cancel-action').onclick=closeActionDialog;$('#edit-cluster-form').onsubmit=async e=>{e.preventDefault();try{await api(`/api/synonym-clusters/${id}`,{method:'PATCH',body:JSON.stringify({terms:parseClusterTerms(new FormData(e.target).get('terms'))})});await loadSynonymClusters();renderSynonymClusters();renderList();closeActionDialog();toast('同义词集群已更新')}catch(err){toast(err.message)}}}
function openDeleteSynonymCluster(id){const cluster=state.synonymClusters.find(c=>c.id===id);if(!cluster)return;openActionDialog('删除同义词集群',`将移除这 ${cluster.terms.length} 个词之间的搜索关联。`,`<div class="dialog-buttons"><button class="button" id="cancel-action">取消</button><button class="button danger-button" id="confirm-delete-cluster">确认删除</button></div>`);$('#cancel-action').onclick=closeActionDialog;$('#confirm-delete-cluster').onclick=async()=>{try{await api(`/api/synonym-clusters/${id}`,{method:'DELETE'});await loadSynonymClusters();renderSynonymClusters();renderList();closeActionDialog();toast('同义词集群已删除')}catch(err){toast(err.message)}}}
function renderThemes(){const box=$('#theme-grid');box.innerHTML=themes.map(t=>`<button class="theme-card ${state.theme===t.id?'active':''}" data-theme-choice="${t.id}"><span class="theme-swatches">${t.swatches.map(c=>`<i style="background:${c}"></i>`).join('')}</span><strong>${esc(t.name)}</strong><small>${esc(t.note)}</small><span class="theme-selected">${state.theme===t.id?'当前使用':'应用配色'}</span></button>`).join('');box.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=async()=>{const id=b.dataset.themeChoice;try{await api('/api/settings/theme',{method:'POST',body:JSON.stringify({theme:id})});applyTheme(id);renderThemes();toast(`已切换为“${themes.find(t=>t.id===id).name}”`)}catch(e){toast(e.message)}})}
function applyTheme(id){state.theme=themes.some(t=>t.id===id)?id:'nocturne';document.documentElement.dataset.theme=state.theme}
function render(){if(state.selected&&!filtered().some(p=>p.id===state.selected))state.selected=null;renderGroups();renderList();renderDetail();$('#crumb-current').textContent=state.view==='aliases'?'同义词集群':state.view==='settings'?'设置':groupName();$('#page-title').textContent=groupName();$('#add-to-group').classList.toggle('hidden',state.groupFilter===null||state.view!=='library');$('#library-view').classList.toggle('hidden',!['library','favorites','recent'].includes(state.view));$('#aliases-view').classList.toggle('hidden',state.view!=='aliases');$('#settings-view').classList.toggle('hidden',state.view!=='settings');$('#sort-order').disabled=state.view==='recent';document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
async function loadPlasmids(){const d=await api('/api/plasmids');state.plasmids=d.plasmids;if(state.selected&&!state.plasmids.some(p=>p.id===state.selected))state.selected=null}
async function loadGroups(){state.groups=await api('/api/groups')}
async function loadSynonymClusters(){state.synonymClusters=await api('/api/synonym-clusters')}
async function loadSettings(){const [storage,theme,sort,close]=await Promise.all([api('/api/storage'),api('/api/settings/theme'),api('/api/settings/sort'),api('/api/settings/close_behavior')]);state.storage=storage;state.sortOrder=sort.sort;state.closeBehavior=close.behavior;$('#repo-path').textContent=storage.path;$('#sort-order').value=sort.sort;applyTheme(theme.theme);document.querySelector(`input[name="close-behavior"][value="${state.closeBehavior}"]`).checked=true}
function dragHasType(event,type){return [...(event.dataTransfer?.types||[])].includes(type)}
function dropGroupAt(target){const row=target?.closest?.('.group-row[data-group]');return row?Number(row.dataset.group):null}
function clearDropVisual(){$('#drop-overlay').classList.add('hidden');document.querySelectorAll('.group-row.drop-target').forEach(row=>row.classList.remove('drop-target'))}
function showDropVisual(groupId){const group=state.groups.find(item=>item.id===groupId);$('#drop-overlay-title').textContent=group?`释放以导入到“${group.name}”`:'释放以导入到总仓库';$('#drop-overlay').classList.remove('hidden');document.querySelectorAll('.group-row.drop-target').forEach(row=>row.classList.remove('drop-target'));if(group)document.querySelector(`.group-row[data-group="${group.id}"]`)?.classList.add('drop-target')}
function closeImportConflict(){$('#import-conflict-modal').classList.add('hidden');$('#import-conflict-content').innerHTML=''}
function openImportConflict(result){clearDropVisual();const {incoming,existing}=result.conflict;$('#import-conflict-title').textContent=`同名文件：${incoming.name}`;$('#import-conflict-progress').textContent=`第 ${result.position} / ${result.total} 个文件 · 请决定保留哪些内容`;
 $('#import-conflict-content').innerHTML=`<div class="conflict-records"><div class="conflict-record conflict-incoming"><strong>本次新导入的文件</strong><span>${esc(incoming.name)}</span><small>${(incoming.size/1024).toFixed(1)} KB · SHA-256 ${esc(incoming.sha256.slice(0,16))}…</small></div><div class="conflict-existing-title">仓库中已有的文件${existing.length>1?' · 请选择一条比较':''}</div>${existing.map((item,index)=>`<label class="conflict-record"><input type="radio" name="conflict-existing" value="${item.id}" ${index===0?'checked':''}/><span><strong>仓库中已有 · #${item.id}</strong><span>${esc(item.name)}</span><small>${(item.size/1024).toFixed(1)} KB · 导入于 ${esc(item.importedAt.slice(0,10))} · SHA-256 ${esc(item.sha256.slice(0,16))}…</small></span></label>`).join('')}</div><div class="conflict-options"><div><strong>保留两份</strong><p>新文件会以“(1)”“(2)”等编号存入仓库。</p><button class="button button-gold" id="conflict-copy" type="button">保留两份并自动编号</button></div><div><strong>只保留一份</strong><p>保留所选原件，或用新文件替换它。替换会保留原有分组、备注和收藏。</p><div class="conflict-choice-buttons"><button class="button" id="conflict-keep" type="button">保留仓库原件</button><button class="button danger-button" id="conflict-replace" type="button">用新文件替换</button></div></div></div><div class="dialog-buttons"><button class="button" id="conflict-cancel" type="button">停止后续导入</button></div>`;
 $('#import-conflict-modal').classList.remove('hidden');$('#conflict-copy').onclick=()=>resolveImportConflict('copy');$('#conflict-keep').onclick=()=>resolveImportConflict('keep_existing');$('#conflict-replace').onclick=()=>resolveImportConflict('replace');$('#conflict-cancel').onclick=cancelPendingImport;$('#conflict-copy').focus()}
async function resolveImportConflict(action){const buttons=[...$('#import-conflict-content').querySelectorAll('button')];buttons.forEach(button=>button.disabled=true);try{const existingId=Number($('#import-conflict-content input[name="conflict-existing"]:checked')?.value)||null;const result=await window.pywebview.api.resolve_import(action,existingId);if(result.error)throw new Error(result.error);await handleImportResult(result)}catch(error){toast(error.message);buttons.forEach(button=>button.disabled=false)}}
async function cancelPendingImport(){try{const result=await window.pywebview.api.cancel_import();closeImportConflict();if(result.cancelled)return;await handleImportResult(result)}catch(error){toast(error.message)}}
async function handleImportResult(result){clearDropVisual();if(result.cancelled)return;if(result.error){toast(result.error);return}if(result.pending){openImportConflict(result);return}closeImportConflict();state.plasmids=result.plasmids;state.previews={};state.selected=null;state.view='library';state.groupFilter=result.groupId??null;state.search='';$('#search').value='';await loadGroups();render();const n=result.imported.length,d=result.duplicates.length,s=result.skipped?.length||0,r=result.replaced?.length||0,g=result.grouped||0,errors=result.errors.length;toast(`${result.cancelledRemaining?'已停止后续导入 · ':''}导入 ${n} 个，重复 ${d} 个${s?`，保留原件 ${s} 个`:''}${r?`，替换 ${r} 个`:''}${g?`，加入分组 ${g} 个`:''}${errors?`，失败 ${errors} 个`:''}`);if(errors)console.warn('导入失败',result.errors)}
async function initialize(){try{await Promise.all([loadSettings(),loadPlasmids(),loadGroups(),loadSynonymClusters()]);render();renderSynonymClusters();renderThemes()}catch(e){$('#plasmid-list').innerHTML=`<div class="no-results">无法连接本机服务：${esc(e.message)}<br/>请启动 Plasmora 桌面程序。</div>`}}
$('#search').addEventListener('input',e=>{state.search=e.target.value.trim();renderList();if(state.selected&&!filtered().some(p=>p.id===state.selected))state.selected=null;renderDetail()});
$('#search-details').onchange=e=>{state.searchDetails=e.target.checked;renderList();if(state.selected&&!filtered().some(p=>p.id===state.selected))state.selected=null;renderDetail()};
$('#import-plasmids').onclick=async()=>{if(!window.pywebview?.api?.import_plasmids){toast('请从 Plasmora 桌面程序导入文件');return}const b=$('#import-plasmids');b.disabled=true;try{await handleImportResult(await window.pywebview.api.import_plasmids())}catch(e){toast(e.message)}finally{b.disabled=false}};
$('#choose-storage').onclick=async()=>{if(!window.pywebview?.api?.choose_storage_directory){toast('请从 Plasmora 桌面程序更改存储位置');return}try{const result=await window.pywebview.api.choose_storage_directory();if(result.cancelled)return;if(result.error)throw new Error(result.error);state.storage={path:result.path};$('#repo-path').textContent=result.path;toast(`存储位置已更新，迁移 ${result.moved} 个文件`)}catch(e){toast(e.message)}};
$('#backup-tools').onclick=openDataTools;$('#bulk-export').onclick=openBulkExport;
document.querySelectorAll('input[name="close-behavior"]').forEach(input=>input.onchange=async()=>{const previous=state.closeBehavior;try{const result=await api('/api/settings/close_behavior',{method:'POST',body:JSON.stringify({behavior:input.value})});state.closeBehavior=result.behavior;toast('关闭方式已保存')}catch(error){state.closeBehavior=previous;document.querySelector(`input[name="close-behavior"][value="${previous}"]`).checked=true;toast(error.message)}});
window.plasmoraShowCloseChoice=()=>{$('#remember-close-choice').checked=false;$('#close-choice-modal').classList.remove('hidden');$('#close-to-tray').focus()};
$('#cancel-close-choice').onclick=()=>$('#close-choice-modal').classList.add('hidden');
for(const [selector,behavior] of [['#close-to-tray','tray'],['#close-quit','quit']])$(selector).onclick=async()=>{const remember=$('#remember-close-choice').checked;if(!window.pywebview?.api?.resolve_close){toast('请在桌面程序中操作');return}try{const result=await window.pywebview.api.resolve_close(behavior,remember);if(result.error)throw new Error(result.error);if(remember){state.closeBehavior=behavior;document.querySelector(`input[name="close-behavior"][value="${behavior}"]`).checked=true}$('#close-choice-modal').classList.add('hidden')}catch(error){toast(error.message)}};
document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.groupFilter=null;render()});$('#add-group').onclick=()=>$('#modal').classList.remove('hidden');$('#close-modal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};$('#group-form').onsubmit=async e=>{e.preventDefault();const name=new FormData(e.target).get('name');try{await api('/api/groups',{method:'POST',body:JSON.stringify({name})});await loadGroups();state.groupFilter=null;state.view='library';e.target.reset();$('#modal').classList.add('hidden');render();toast('分组已创建')}catch(err){toast(err.message)}};$('#cluster-form').onsubmit=async e=>{e.preventDefault();try{const terms=parseClusterTerms(new FormData(e.target).get('terms'));await api('/api/synonym-clusters',{method:'POST',body:JSON.stringify({terms})});await loadSynonymClusters();e.target.reset();renderSynonymClusters();renderList();toast('同义词集群已保存')}catch(err){toast(err.message)}};$('#sort-order').onchange=async e=>{const previous=state.sortOrder;state.sortOrder=e.target.value;renderList();try{await api('/api/settings/sort',{method:'POST',body:JSON.stringify({sort:state.sortOrder})})}catch(err){state.sortOrder=previous;e.target.value=previous;renderList();toast(err.message)}};initialize();
$('#add-to-group').onclick=()=>{if(state.groupFilter!==null)openGroupPicker(state.groupFilter)};$('#close-action').onclick=closeActionDialog;$('#action-modal').onclick=e=>{if(e.target.id==='action-modal')closeActionDialog()};
document.addEventListener('pointerdown',e=>{if(!$('#context-menu').contains(e.target))closeContextMenu()});
document.addEventListener('scroll',closeContextMenu,true);window.addEventListener('resize',closeContextMenu);window.addEventListener('blur',closeContextMenu);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#import-conflict-modal').classList.contains('hidden')){cancelPendingImport();e.preventDefault();return}const menu=$('#context-menu');if(e.key==='Escape'){if(!menu.classList.contains('hidden')){closeContextMenu();e.preventDefault()}else closeActionDialog()}if(!menu.classList.contains('hidden')&&(e.key==='ArrowDown'||e.key==='ArrowUp')){const buttons=[...menu.querySelectorAll('button')],index=buttons.indexOf(document.activeElement);buttons[(index+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length]?.focus();e.preventDefault()}});
window.plasmoraDropGroupId=null;
window.plasmoraDropCompleted=handleImportResult;
$('#close-import-conflict').onclick=cancelPendingImport;$('#import-conflict-modal').onclick=event=>{if(event.target.id==='import-conflict-modal')cancelPendingImport()};
document.addEventListener('dragenter',event=>{if(dragHasType(event,'Files'))showDropVisual(dropGroupAt(event.target))},true);
document.addEventListener('dragover',event=>{const groupId=dropGroupAt(event.target);if(dragHasType(event,'Files')){event.preventDefault();event.dataTransfer.dropEffect='copy';window.plasmoraDropGroupId=groupId;showDropVisual(groupId)}else if(dragHasType(event,'application/x-plasmora-id')){clearDropVisual();if(groupId!==null){event.preventDefault();event.dataTransfer.dropEffect='copy';document.querySelector(`.group-row[data-group="${groupId}"]`)?.classList.add('drop-target')}}},true);
document.addEventListener('dragleave',event=>{if(!event.relatedTarget)clearDropVisual()},true);
document.addEventListener('drop',async event=>{const groupId=dropGroupAt(event.target);if(dragHasType(event,'Files')){event.preventDefault();window.plasmoraDropGroupId=groupId;clearDropVisual();return}const id=Number(event.dataTransfer?.getData('application/x-plasmora-id'));if(!id)return;event.preventDefault();clearDropVisual();if(groupId===null)return;try{await api(`/api/groups/${groupId}/plasmids`,{method:'POST',body:JSON.stringify({plasmid_id:id})});await Promise.all([loadGroups(),loadPlasmids()]);render();toast('已加入分组')}catch(error){toast(error.message)}},true);
